#include "main.h"
#include "motors.h"

using namespace pros;

Motor left_wheels_1 (MOTOR1, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES); //L1
Motor right_wheels_1 (MOTOR3, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES); //R1
Motor left_wheels_2 (MOTOR2, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES); //L2
Motor right_wheels_2 (MOTOR4, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES); //R2

Motor intake_left (MOTOR7, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor intake_right (MOTOR8, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor arm (MOTOR6, E_MOTOR_GEARSET_36, 1, E_MOTOR_ENCODER_DEGREES);
Motor angler (MOTOR5, E_MOTOR_GEARSET_36, 0, E_MOTOR_ENCODER_DEGREES);
